replicaCount: 1

image:
  repository: postgres
  tag: 16.2-alpine3.19
  pullPolicy: IfNotPresent

service:
  port: 5432

env:
  POSTGRES_USER: devops #  Valeurs par défaut 
  POSTGRES_PASSWORD: devops #  Valeurs par défaut
  POSTGRES_DB: catalogue #  Valeurs par défaut
