image:
  repository: postgres
  tag: 16.2-alpine3.19
  pullPolicy: IfNotPresent
replicaCount: 1

service:
  port: 5432

env:
  POSTGRES_USER: <path:secret/catalogue-db/dev#POSTGRES_USER>          
  POSTGRES_PASSWORD: <path:secret/catalogue-db/dev#POSTGRES_PASSWORD> 
  POSTGRES_DB: <path:secret/catalogue-db/dev#POSTGRES_DB>             
