replicaCount: 1

image:
  repository: mohamedgharbii/frontend
  tag: latest
  pullPolicy: Always

service:
  type: NodePort
  port: 30080 
  nodePort: 31987         
# staging
service:
  type: NodePort
  port: 30080
  nodePort: 31988

# prod
service:
  type: NodePort
  port: 30080
  nodePort: 31989
resources:
  limits:
    memory: "512Mi"
  requests:
    cpu: "200m"
    memory: "256Mi"
